version: "3.8"
services:
  calibre:
    image: linuxserver/calibre:${CALIBRE_VERSION}
    container_name: calibre
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${CALIBRE_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/calibre/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/calibre/config:/config:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/Comics:/comics:z
      - ${MEDIA_FOLDER}/eBooks:/ebooks:z

  calibre-web:
    image: linuxserver/calibre-web:${CALIBREWEB_VERSION}
    container_name: calibre-web
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${CALIBREWEB_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/calibre-web/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/calibre-web/config:/config:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/Comics:/comics:z
      - ${MEDIA_FOLDER}/eBooks:/ebooks:z

  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    container_name: flaresolverr
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${FLARESOLVERR_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/flaresolverr/.env"]
    environment: ["TZ: ${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/jackett/config:/config:z

  jackett:
    image: linuxserver/jackett:${JACKETT_VERSION}
    container_name: jackett
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${JACKETT_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/jackett/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/jackett/config:/config:z
      - ${TORRENT_BLACKHOLE_FOLDER}:/blackhole:z

  lazylibrarian:
    image: linuxserver/lazylibrarian:${LAZYLIBRARIAN_VERSION}
    container_name: lazylibrarian
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${LAZYLIBRARIAN_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/lazylibrarian/.env"]
    environment:
      PUID: ${UID}
      PGID: ${GID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
      DOCKER_MODS: ghcr.io/linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #needed for calibredb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/lazylibrarian/config:/config:z
      - ${TORRENT_BLACKHOLE_FOLDER}:/torrent/blackhole:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/eBooks:/downloads/completed/eBooks:z
      - ${USENET_BLACKHOLE_FOLDER}:/usenet/blackhole:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/Comics:/comics:z
      - ${MEDIA_FOLDER}/eBooks:/ebooks:z

  lidarr:
    image: linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${LIDARR_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/lidarr/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/lidarr/config:/config:z
      - ${RECYCLE_FOLDER}/lidarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Lidarr:/downloads/completed/Lidarr:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Music:/downloads/completed/Music:z
      - ${MEDIA_FOLDER}/Music:/music:z

  mylar:
    image: linuxserver/mylar3:${MYLAR_VERSION}
    container_name: mylar
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${MYLAR_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/mylar/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/mylar/config:/config:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${MEDIA_FOLDER}/Comics:/comics:z

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${NGINX_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: [".env", "${CONFIG_FOLDER}/nginx/.env"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/nginx/templates:/etc/nginx/templates:z

  nzbget:
    image: linuxserver/nzbget:${NZBGET_VERSION}
    container_name: nzbget
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${NZBGET_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/nzbget/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/nzbget/config:/config:z
      - ${USENET_BLACKHOLE_FOLDER}:/blackhole:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/Comics:/comics:z
      - ${MEDIA_FOLDER}/eBooks:/ebooks:z
      - ${MEDIA_FOLDER}/Movies:/movies:z
      - ${MEDIA_FOLDER}/Music:/music:z
      - ${MEDIA_FOLDER}/Series:/series:z

  nzbhydra2:
    image: linuxserver/nzbhydra2:${NZBHYDRA2_VERSION}
    container_name: nzbhydra2
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${NZBHYDRA2_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/nzbhydra2/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/nzbhydra2/config:/config:z
      - ${TORRENT_BLACKHOLE_FOLDER}:/downloads/torrent/blackhole:z
      - ${USENET_BLACKHOLE_FOLDER}:/downloads/usenet/blackhole:z

  plex:
    image: linuxserver/plex:${PLEX_VERSION}
    container_name: plex
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${PLEX_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    # Leave commented unless your machine is capable of Hardware acceleration - Intel / Nvidia
    # More information at; https://github.com/linuxserver/docker-plex#hardware-acceleration
    # devices: [ "/dev/dri:/dev/dri" ] # Intel QuickSync
    env_file: ["${CONFIG_FOLDER}/plex/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/plex/config:/config:z
      - ${CONFIG_FOLDER}/plex/transcode:/transcode:z
      - ${MEDIA_FOLDER}/Series:/data/Series:z
      - ${MEDIA_FOLDER}/Movies:/data/Movies:z
      - ${MEDIA_FOLDER}/Music:/data/Music:z

  protonvpn:
    image: ghcr.io/tprasadtp/protonwire:${PROTONVPN_VERSION}
    container_name: protonvpn
    restart: unless-stopped
    profiles: ["${PROTONVPN_PROFILE}"]
    env_file: [".env", "${CONFIG_FOLDER}/protonvpn/.env"]
    cap_add: [NET_ADMIN]
    sysctls:
      ["net.ipv6.conf.all.disable_ipv6=1", "net.ipv4.conf.all.rp_filter=2"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp:z
    ports:
      - ${CALIBRE_HTTP_PORT}:${CALIBRE_HTTP_PORT}                             # calibre
      - ${CALIBRE_WEB_CONTAINER_HTTP_PORT}:${CALIBRE_WEB_CONTAINER_HTTP_PORT} # calibre-web (from calibre-web container)
      - ${CALIBRE_WEB_HTTP_PORT}:${CALIBRE_WEB_HTTP_PORT}                     # calibre-web (from calibre)
      - ${FLARESOLVERR_HTTP_PORT}:${FLARESOLVERR_HTTP_PORT}                   # flaresolverr-http
      - ${JACKETT_HTTP_PORT}:${JACKETT_HTTP_PORT}                             # jackett-http
      - ${LAZYLIBRARIAN_HTTP_PORT}:${LAZYLIBRARIAN_HTTP_PORT}                 # lazylibrarian
      - ${LIDARR_HTTP_PORT}:${LIDARR_HTTP_PORT}                               # lidarr-http
      - ${LIDARR_HTTPS_PORT}:${LIDARR_HTTPS_PORT}                             # lidarr-https
      - ${MYLAR_HTTP_PORT}:${MYLAR_HTTP_PORT}                                 # mylar-http
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}                                 # nginx-http
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTP_PORT}                                # nginx-https
      - ${NZBGET_HTTP_PORT}:${NZBGET_HTTP_PORT}                               # nzbget-http
      - ${NZBGET_HTTPS_PORT}:${NZBGET_HTTPS_PORT}                             # nzbget-https
      - ${NZBHYDRA2_HTTP_PORT}:${NZBHYDRA2_HTTP_PORT}                         # nzbhydra2-http or nzbhydra2-https
      - ${QBITTORRENT_HTTP_PORT}:${QBITTORRENT_HTTP_PORT}                     # qbittorrent-http
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}                               # qbittorrent-torrent
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp                           # qbittorrent-torrent
      - ${RADARR_HTTP_PORT}:${RADARR_HTTP_PORT}                               # radarr-http
      - ${RADARR_HTTPS_PORT}:${RADARR_HTTPS_PORT}                             # radarr-https
      - ${READARR_HTTP_PORT}:${READARR_HTTP_PORT}                             # readarr-http
      - ${READARR_HTTPS_PORT}:${READARR_HTTPS_PORT}                           # readarr-https
      - ${SONARR_HTTP_PORT}:${SONARR_HTTP_PORT}                               # sonarr-http
      - ${SONARR_HTTPS_PORT}:${SONARR_HTTPS_PORT}                             # sonarr-https
      - 8324:8324 # plex
      - 1900:1900/udp # plex
      - 3005:3005 # plex
      # - 5353:5353/udp   # plex
      - 32400:32400 # plex
      - 32410:32410/udp # plex
      - 32412:32412/udp # plex
      - 32413:32413/udp # plex
      - 32414:32414/udp # plex
      - 32469:32469 # plex

  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${QBITTORRENT_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/qbittorrent/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/qbittorrent/config:/config:z
      - ${TORRENT_BLACKHOLE_FOLDER}:/blackhole:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/eBooks:/books:z
      - ${MEDIA_FOLDER}/Movies:/movies:z
      - ${MEDIA_FOLDER}/Music:/music:z
      - ${MEDIA_FOLDER}/Series:/tv:z

  radarr:
    image: linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${RADARR_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/radarr/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/radarr/config:/config:z
      - ${RECYCLE_FOLDER}/radarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Radarr:/downloads/completed/Radarr:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Movies:/downloads/completed/Movies:z
      - ${MEDIA_FOLDER}/Movies:/movies:z

  readarr:
    image: linuxserver/readarr:${READARR_VERSION}
    container_name: readarr
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${READARR_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/readarr/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/readarr/config:/config:z
      - ${RECYCLE_FOLDER}/readarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Readarr:/downloads/completed/Readarr:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Readarr:/downloads/completed/eBooks:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/Comics:/comics:z
      - ${MEDIA_FOLDER}/eBooks:/books:z

  sonarr:
    image: linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    depends_on: ["${VPN_PROVIDER}"]
    profiles: ["${SONARR_PROFILE}"]
    network_mode: service:${VPN_PROVIDER}
    sysctls: ["net.ipv6.conf.all.disable_ipv6=1"]
    restart: unless-stopped
    env_file: ["${CONFIG_FOLDER}/sonarr/.env"]
    environment:
      ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/sonarr/config:/config:z
      - ${RECYCLE_FOLDER}/sonarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Sonarr:/downloads/completed/Sonarr:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Series:/downloads/completed/Series:z
      - ${MEDIA_FOLDER}/Series:/series:z
