blank_issues_enabled: false

contact_links:
  - name: Consider contributing / donating
    url: https://github.com/sponsors/ivan-pinatti
    about: |-
      I code this on my free time, please consider donating or sponsoring to support the project
